version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: excalidraw-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: excalidraw_user
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: excalidraw_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U excalidraw_user -d excalidraw_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
